/**
 * Regenerate test/fixtures/search-parity.json.
 *
 * The corpus (`docs`) and the query set (each `q` + `k`) are the fixed inputs
 * and are read back from the existing fixture; only the expected `results`
 * (ranked uri + score per query) are recomputed by running the current
 * IndexSearch over the corpus. Run this after any intentional ranking change:
 *
 *   npx tsx test/fixtures/generate-search-parity.ts
 *
 * search.test.ts then locks ranking against this snapshot, so future
 * unintended ranking regressions are caught.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { IndexSearch, type Doc } from "../../src/utils/indexer.js";

interface Query {
  q: string;
  k: number;
  results?: { uri: string; score: number }[];
}

interface Fixture {
  _description?: string;
  docCount: number;
  docs: Doc[];
  queries: Query[];
}

const fixturePath = fileURLToPath(new URL("./search-parity.json", import.meta.url));
const fixture = JSON.parse(readFileSync(fixturePath, "utf8")) as Fixture;

const ix = new IndexSearch();
for (const d of fixture.docs) ix.add(d);

const queries = fixture.queries.map((query) => ({
  q: query.q,
  k: query.k,
  results: ix.search(query.q, query.k).map((r) => ({ uri: r.doc.uri, score: r.score })),
}));

const out: Fixture = {
  _description:
    "IndexSearch.search(q,k) ranking snapshot, regenerated by " +
    "test/fixtures/generate-search-parity.ts after the BM25 ranking fix " +
    "(deduplicated postings + token-based weighted term frequencies). The " +
    "corpus and queries are the fixed inputs; results are recomputed. Scores " +
    "must match within 1e-12.",
  docCount: fixture.docs.length,
  docs: fixture.docs,
  queries,
};

writeFileSync(fixturePath, JSON.stringify(out, null, 2) + "\n");
console.error(`wrote ${fixturePath}: ${out.docCount} docs, ${queries.length} queries`);
